databaseChangeLog:
  - changeSet:
      id: 005-create-table-configuration_raw
      author: pas-zhukov
      changes:
        - createTable:
            tableName: configuration_raw
            columns:
              - column:
                  name: id
                  type: BIGSERIAL
                  constraints:
                    primaryKey: true
                    nullable: false

              - column:
                  name: source_id
                  type: BIGINT
                  constraints:
                    nullable: false
              - column:
                  name: name
                  type: VARCHAR(255)
              - column:
                  name: url
                  type: TEXT
              - column:
                  name: buy_url
                  type: TEXT
              - column:
                  name: thumb
                  type: TEXT
              - column:
                  name: price
                  type: DECIMAL(10,2)
              - column:
                  name: price_list
                  type: DECIMAL(10,2)
              - column:
                  name: brand
                  type: VARCHAR(255)
              - column:
                  name: cpu
                  type: TEXT
              - column:
                  name: gpu
                  type: TEXT
              - column:
                  name: display_size
                  type: DECIMAL(5,1)
              - column:
                  name: display_resolution
                  type: VARCHAR(255)
              - column:
                  name: display_name
                  type: TEXT
              - column:
                  name: panel_type
                  type: VARCHAR(50)
              - column:
                  name: panel_code
                  type: DECIMAL(5,1)
              - column:
                  name: refresh_rate
                  type: INTEGER
              - column:
                  name: storage_ssd
                  type: DECIMAL(10,1)
              - column:
                  name: storage_hdd
                  type: DECIMAL(10,1)
              - column:
                  name: ram
                  type: DECIMAL(5,1)
              - column:
                  name: weight
                  type: DECIMAL(5,2)
              - column:
                  name: suitable_for
                  type: TEXT
              - column:
                  name: pop_searches
                  type: TEXT
              - column:
                  name: show_our
                  type: TEXT
              - column:
                  name: is_new
                  type: BOOLEAN
              - column:
                  name: last_upd
                  type: TEXT

  - changeSet:
      id: 005-insert-raw-configurations-data
      author: pas-zhukov
      changes:
        - loadData:
            tableName: configuration_raw
            file: csv/thinkpad_laptops.csv
            relativeToChangelogFile: true
            separator: ","
            quotchar: '"'
            usePreparedStatements: true
            columns:
              - column:
                  name: source_id
                  type: NUMERIC
              - column:
                  name: name
                  type: STRING
              - column:
                  name: url
                  type: STRING
              - column:
                  name: buy_url
                  type: STRING
              - column:
                  name: thumb
                  type: STRING
              - column:
                  name: price
                  type: NUMERIC
              - column:
                  name: price_list
                  type: NUMERIC
              - column:
                  name: brand
                  type: STRING
              - column:
                  name: cpu
                  type: STRING
              - column:
                  name: gpu
                  type: STRING
              - column:
                  name: display_size
                  type: NUMERIC
              - column:
                  name: display_resolution
                  type: STRING
              - column:
                  name: display_name
                  type: STRING
              - column:
                  name: panel_type
                  type: STRING
              - column:
                  name: panel_code
                  type: NUMERIC
              - column:
                  name: refresh_rate
                  type: NUMERIC
              - column:
                  name: storage_ssd
                  type: NUMERIC
              - column:
                  name: storage_hdd
                  type: NUMERIC
              - column:
                  name: ram
                  type: NUMERIC
              - column:
                  name: weight
                  type: NUMERIC
              - column:
                  name: suitable_for
                  type: STRING
              - column:
                  name: pop_searches
                  type: STRING
              - column:
                  name: show_our
                  type: STRING
              - column:
                  name: is_new
                  type: BOOLEAN
              - column:
                  name: last_upd
                  type: STRING
